[build]
  # Directorio de publicación (donde están los archivos del sitio)
  publish = "."
  
  # No necesitamos comando de build ya que es una aplicación estática
  command = ""

# Configuración básica de headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
