[build]
  # Directorio de publicación (donde están los archivos del sitio)
  publish = "."
  
  # No necesitamos comando de build ya que es una aplicación estática
  command = ""

[build.environment]
  # Variables de entorno si las necesitamos en el futuro
  NODE_VERSION = "18"

# Configuración de headers para mejor seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache para archivos estáticos
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300"

# Redirecciones (por si necesitamos agregar rutas en el futuro)
[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

# Configuración para SPA (Single Page Application) si es necesario
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Configuración de funciones (si las agregamos en el futuro)
[functions]
  directory = "netlify/functions"
